import type { CalendarEvent, OverlayCalendar } from "./types";

/**
 * Sample events for local dev and preview.
 * Delete this file after the Trumba migration is complete.
 */

export const SAMPLE_OVERLAYS: OverlayCalendar[] = [
  { id: "sample-overlay-movement",      name: "Movement Calendar",           slug: "movement",       color: "#39375b", default_visible: true,  sort_order: 1, description: null },
  { id: "sample-overlay-congress",      name: "Congressional Schedule",      slug: "congressional",  color: "#e879a1", default_visible: true,  sort_order: 2, description: null },
  { id: "sample-overlay-elections",     name: "Elections",                   slug: "elections",      color: "#10b981", default_visible: true,  sort_order: 3, description: null },
  { id: "sample-overlay-events",        name: "Events, Meetings, Festivals", slug: "events-meetings", color: "#06b6d4", default_visible: true,  sort_order: 4, description: null },
  { id: "sample-overlay-holidays",      name: "Holidays",                    slug: "holidays",       color: "#ec4899", default_visible: true,  sort_order: 5, description: null },
  { id: "sample-overlay-recurring",     name: "Recurring Events",            slug: "recurring",      color: "#a78bfa", default_visible: true,  sort_order: 6, description: null },
  { id: "sample-overlay-scotus",        name: "SCOTUS",                      slug: "scotus",         color: "#1e40af", default_visible: true,  sort_order: 7, description: null },
  { id: "sample-overlay-sports",        name: "Sports",                      slug: "sports",         color: "#3b82f6", default_visible: false, sort_order: 8, description: null },
];

const OVERLAY_MOVEMENT = SAMPLE_OVERLAYS[0];
const OVERLAY_CONGRESS = SAMPLE_OVERLAYS[1];
const OVERLAY_SCOTUS = SAMPLE_OVERLAYS[6];

const TYPE_ACTION = {
  id: "sample-type-action",
  name: "Action",
  slug: "action",
  color: null,
  sort_order: 1,
};
const TYPE_MEETING = {
  id: "sample-type-meeting",
  name: "Meeting",
  slug: "meeting",
  color: null,
  sort_order: 5,
};
const TYPE_TRAINING = {
  id: "sample-type-training",
  name: "Training",
  slug: "training",
  color: null,
  sort_order: 8,
};

// Build sample event dates relative to "now" so the feed always looks alive.
function daysFromNow(days: number, hour = 18): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const SAMPLE_EVENTS: CalendarEvent[] = [
  {
    id: "s1",
    title: "MIP Monthly Organizing Meeting",
    slug: "mip-monthly-organizing-meeting",
    description: "Join us for our monthly organizing meeting to hear updates and shape priorities.",
    starts_at: daysFromNow(2, 19),
    ends_at: daysFromNow(2, 21),
    all_day: false,
    timezone: "America/New_York",
    location_type: "in_person",
    location_text: "33 Grant Circle NW, Washington DC",
    location_lat: null,
    location_lng: null,
    image_url:
      "https://images.unsplash.com/photo-1591189863430-ab87e120f312?w=400&h=400&fit=crop",
    event_type_id: TYPE_MEETING.id,
    event_type: TYPE_MEETING,
    cost: "Free",
    host_org: "Movement Infrastructure Project",
    accessibility: ["physical_access", "childcare"],
    web_link: null,
    overlay_calendar_id: OVERLAY_MOVEMENT.id,
    overlay_calendar: OVERLAY_MOVEMENT,
    is_featured: true,
    featured_until: daysFromNow(3),
    featured_sort_order: 1,
    status: "published",
    source: "admin",
    external_id: null,
    rrule: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "s2",
    title: "Know Your Rights Training",
    slug: "know-your-rights-training",
    description: "Learn your rights when interacting with law enforcement.",
    starts_at: daysFromNow(4, 18),
    ends_at: daysFromNow(4, 20),
    all_day: false,
    timezone: "America/New_York",
    location_type: "hybrid",
    location_text: "Festival Center, 1640 Columbia Rd NW",
    location_lat: null,
    location_lng: null,
    image_url:
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=400&fit=crop",
    event_type_id: TYPE_TRAINING.id,
    event_type: TYPE_TRAINING,
    cost: "Free",
    host_org: "Free DC",
    accessibility: ["asl", "spanish", "physical_access"],
    web_link: null,
    overlay_calendar_id: OVERLAY_MOVEMENT.id,
    overlay_calendar: OVERLAY_MOVEMENT,
    is_featured: true,
    featured_until: daysFromNow(5),
    featured_sort_order: 2,
    status: "published",
    source: "admin",
    external_id: null,
    rrule: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "s3",
    title: "Boycott Target DMV Picket",
    slug: "boycott-target-dmv-picket",
    description: "Weekly picket at 14th St. Target.",
    starts_at: daysFromNow(6, 12),
    ends_at: daysFromNow(6, 14),
    all_day: false,
    timezone: "America/New_York",
    location_type: "in_person",
    location_text: "3100 14th St NW",
    location_lat: null,
    location_lng: null,
    image_url: null,
    event_type_id: TYPE_ACTION.id,
    event_type: TYPE_ACTION,
    cost: null,
    host_org: null,
    accessibility: [],
    web_link: null,
    overlay_calendar_id: OVERLAY_MOVEMENT.id,
    overlay_calendar: OVERLAY_MOVEMENT,
    is_featured: false,
    featured_until: null,
    featured_sort_order: null,
    status: "published",
    source: "admin",
    external_id: null,
    rrule: "FREQ=WEEKLY;BYDAY=SA",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "s4",
    title: "House in Session",
    slug: "house-in-session-1",
    description: null,
    starts_at: daysFromNow(3, 9),
    ends_at: daysFromNow(3, 18),
    all_day: false,
    timezone: "America/New_York",
    location_type: null,
    location_text: "US Capitol",
    location_lat: null,
    location_lng: null,
    image_url: null,
    event_type_id: null,
    event_type: undefined,
    cost: null,
    host_org: null,
    accessibility: [],
    web_link: null,
    overlay_calendar_id: OVERLAY_CONGRESS.id,
    overlay_calendar: OVERLAY_CONGRESS,
    is_featured: false,
    featured_until: null,
    featured_sort_order: null,
    status: "published",
    source: "admin",
    external_id: null,
    rrule: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "s5",
    title: "SCOTUS Oral Arguments",
    slug: "scotus-oral-arguments-1",
    description: "Supreme Court oral argument day.",
    starts_at: daysFromNow(5, 10),
    ends_at: daysFromNow(5, 15),
    all_day: false,
    timezone: "America/New_York",
    location_type: "in_person",
    location_text: "Supreme Court of the United States",
    location_lat: null,
    location_lng: null,
    image_url: null,
    event_type_id: null,
    event_type: undefined,
    cost: null,
    host_org: null,
    accessibility: [],
    web_link: null,
    overlay_calendar_id: OVERLAY_SCOTUS.id,
    overlay_calendar: OVERLAY_SCOTUS,
    is_featured: false,
    featured_until: null,
    featured_sort_order: null,
    status: "published",
    source: "admin",
    external_id: null,
    rrule: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "s6",
    title: "Movement Block Party and Organizing Fair",
    slug: "movement-block-party",
    description: "Block party with food, drinks, cornhole tournament, and tables from local groups.",
    starts_at: daysFromNow(10, 14),
    ends_at: daysFromNow(10, 18),
    all_day: false,
    timezone: "America/New_York",
    location_type: "in_person",
    location_text: "33 Grant Circle NW",
    location_lat: null,
    location_lng: null,
    image_url:
      "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=400&h=400&fit=crop",
    event_type_id: TYPE_ACTION.id,
    event_type: TYPE_ACTION,
    cost: "Free",
    host_org: "Movement Infrastructure Project",
    accessibility: ["physical_access", "childcare", "spanish"],
    web_link: null,
    overlay_calendar_id: OVERLAY_MOVEMENT.id,
    overlay_calendar: OVERLAY_MOVEMENT,
    is_featured: false,
    featured_until: null,
    featured_sort_order: null,
    status: "published",
    source: "admin",
    external_id: null,
    rrule: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
